---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencsp-console
  namespace: opencsp-console
spec:
  interval: 1h
  chart:
    spec:
      chart: opencsp-console
      version: "0.1.14"
      sourceRef:
        kind: HelmRepository
        name: opencsp-console
        namespace: flux-system
  values:
    be:
      image:
        tag: "0.1.14"
      env:
        APP_IAM_PROVIDER: "none"
        APP_K8S_ENABLED: "true"
      existingSecret: "opencsp-be-secret"

    fe:
      image:
        tag: "0.1.14"
      env:
        NEXTAUTH_URL: "https://opencsp.avgmax.team"
      existingSecret: "opencsp-fe-secret"

    ingress:
      enabled: true
      className: "cilium"
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-issuer"
        ingress.cilium.io/backend-protocol: "http"
      tls:
        - hosts:
            - opencsp.avgmax.team
          secretName: opencsp-console-tls
      hosts:
        - host: opencsp.avgmax.team
          paths:
            - path: /api/console/ws
              pathType: Prefix
              backend:
                service:
                  name: opencsp-console-be
                  port:
                    number: 8080
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: opencsp-console-fe
                  port:
                    number: 3000

    pam:
      provider: teleport
      identityMountPath: /var/pam/identity
      teleport:
        authServer: "teleport-teleport-cluster-auth.teleport.svc.cluster.local:3025"
        token: "opencsp-be-bot"
        serviceAccountName: opencsp-tbot
        image:
          tag: "18.6.4"