apiVersion: ENC[AES256_GCM,data:wyk=,iv:f2NDb56oGDnPBqFQpQ4wXS1e+kGmDEi8OmoJFwwgCJI=,tag:eWVsj/u+jCJPbsI4zTH8kA==,type:str]
kind: ENC[AES256_GCM,data:QUlO5q6d,iv:YCLFJS/XbPfLSP7VW0m8OLdDN21bZX0EjphmNAyWAno=,tag:4kcTq0fRm9xrcyscvXQ2cg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yHQL8xD/NAPSyLbYCaHutzI=,iv:lLHlTXtySZJZSd2vyep9PvKUvGe8JJTMcLnqEb69QgA=,tag:+xVMWFPW8NiPpYLRQvZD5A==,type:str]
    namespace: ENC[AES256_GCM,data:RYkWNF1Utr29N244ey2Z,iv:cto5dxwft1URMAUTRVQAVz/mxpemq5vqo08iQx8PCvY=,tag:xLuMZKNhho0FECWqr2AL+Q==,type:str]
stringData:
    APP_K8S_API_SERVER: ENC[AES256_GCM,data:IvVU7vdMmD4AY3itIpH0DkOyFwq9Znde3pE=,iv:68bKpa711e+Cdd23KMoYrpHooe62L8haketKczUR6ZM=,tag:ptH8hhkx1sq4f2KpgMydCg==,type:str]
    APP_K8S_TOKEN: ENC[AES256_GCM,data:PjeOob90mC6A23/w5PKT8EQlvGicjv2xymX6skevPjjxJ36+7oANNNFiDcqB2L1QxLHRcWbVCJ3VCgJzGiymhRRZHLonAniUDqx3zSW2tUohmfK259z/LqMK2l1DpUWWQYVFQWZC0u9aRE0SLwQZQ2vwJjciLvBV7YiIUjSMm73hDtk0QjOhDS3jV26JfgOXz1DSqs11bxBdylWCg2VbNkbCvopA5MaLQ8jfCe71AXaiqZEOU5DiodtFsdzmlp4Akob0f5gPG2dZRIBjn7QA7CU8MqT9wVENTFOktQ84/JxApsyBjac8/BYO6fwbQo1UmEwCyU3ZpphmfCPdNN72agLMde1Nr9Dm6thj05ttzdGpYl/GqwoOP//pCidJEpIzYCLFxi3nTwbsCa+QOwCQokDnh2YpIzDORicl1+8GGddsLaeKex5QIkYtJgGXgGUd5zItAmi4Gt/RKuN2DexrcWkiMHrw8g/SS4NFTuUgKFjEcfaKfSc+eyxU7dZBxuZ6JfU0TOkYdt8LRtCSWr0lrJLBM+bCztZa/S3agBDZwnwp4XkYuEmU5Ga9RExPAzELIaBxGKcNNSTKPZhNa55xdA/c6mlnYjpEGIC+w8okYAtmPQ6MbJ77wJ4Cz/P98GRXMdiwZnQ/RABDmfEu2Schqsu2RqyjGsj+PCWtpcuZZfRbSBb+IUJNUaPrGVnMqoCNGIrRevf3G4nIq9HL/QP9UnJfxshhDLk8b63LjBi/y45SHZTD8LqwO8goboCBvvyDA31KZed8fxDSu0xRjyeKXPztTEvtyxaOH1wjVfEu9wxFx4feQzKJKhixm5zmOAdc4h2xY6myETji5ooL0p7gwd4aL56Uv15Z46rBL7uNoI9lLLD7kVAMK2CdhpLvqF9CK8J5iSkIsV4HZguD/fKELQa6Ngn3wDBoPTyIn895z8uaMKkGey0pMWklJKlOVu6Wuksts4XaxlIcLTKoMCydN6IviX+lYHdD1Gq+iRWV1RLiS019hvrOXUqjDFOuwnlmPgE7Otvyee/UAPWcDMQD8Nc/LR0xhm2MPityBdBuei24y74PrZEba22hlwzdB4vH2sj2OWsym/jc1Rw+/HyWoChG50V1sutwkcVONMeQLaza74NEv0RsqmugqIxCBqpmVzdJ7Iw3tJQLWg3Uo9Kmx6tEpeYAKE62hsMt7bA5kXJuoiKoUUwhe4BbfRVG0PEvBRpeRvWs69rWmvxdTPNOB+T8RxtNhTQHZy+c9drj,iv:dEnmodn70XfjokOFXJRi3oCim8PIXyWfac3KxSHCGKY=,tag:M2D53KRRMOkM12KBYNvekA==,type:str]
    APP_K8S_TRUST_CERTS: ENC[AES256_GCM,data:853TGg==,iv:2K8GVM9Lp+WVmvf+AbnOazHvbGsgh2ryMINWa8n87mM=,tag:dv9OBTM3oBJKpmpa/5Pktw==,type:str]
    APP_CONFIG_ENCRYPTION_KEY: ""
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:VzNnY/hSVOgC7oeDMZnvIcH/jnG7ILTYOK0rJRgBHhX/jYH9TGFq6l7P2fHHUtE4LGkAK06yWx5TEEXO6/4=,iv:YMQcyTRh8whtU0Qq6+QNSBM7Z90tTo6Mj8FWKlhfVWI=,tag:QqVTxTDdFq4A8TvUqCfFtQ==,type:str]
    SPRING_DATASOURCE_DRIVER: ENC[AES256_GCM,data:zYil4GiUObT3oC3HeHwV,iv:bK69ng7vuDq1LbZ+r4BE/sxu/ppRbNcqAz0hXYiP8d4=,tag:gS8IBmoL8GXBt67PyyZHFg==,type:str]
    SPRING_JPA_DIALECT: ENC[AES256_GCM,data:0M5CIyQbGE0nWILsnBrBywtO397lKHbDZ8RQ7+fWlGjEZFlkuFGT4N2lC7Tf,iv:2FyG7hEBJ0mRRt6Ny9RtLi2DJhaz5wYjnDxgD9pK/yM=,tag:2FO6IybJ4kvT7/Dtul+jMg==,type:str]
    SPRING_JPA_HIBERNATE_DDL_AUTO: ENC[AES256_GCM,data:n/989qO8,iv:n05W+vQ2tZdVHdhpJkydWs6CszaUSY7J2MpzEge7BrE=,tag:Gq1Je2PPoHSTqAUokxY8Ow==,type:str]
    SPRING_JPA_SHOW_SQL: ENC[AES256_GCM,data:XMXHaZE=,iv:q84x0jUOYM+tLz2UtHGo0WYiLMXeJZtWbkwu7j3b3MQ=,tag:Zpe+HSxXytMzol/oRMOXVA==,type:str]
    APP_AI_ENABLED: ENC[AES256_GCM,data:ZHaAaZM=,iv:o7bEM9mtbQUomoO9oTCYD85g40SccgOLV6XMi0vuCf4=,tag:KcsRLVfLwU6aRXg+e7lU1g==,type:str]
    SPRING_AI_OPENAI_API_KEY: ""
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT2hIem43RmlSdlJnU2ln
            YWx0bEpuSEpEL3JscTE0ZFdUOTI0RmhjblJZCnBDcnJSNHg5VnFZN2pkNStuWHJH
            T0sySC85b0pkZnlUTzM4ZjRRTU9vRjQKLS0tIHhXeW50ejE2a2Y3bEU5MHdGcGtQ
            TlNhNkR3MmtyV2hhM3hCeDg0eVUrczAKnHZjIgCyoluvRjpUJQVIhlaW9idXtHle
            yQAYO5bvtjeEukq68lmHozsyVlTCHDs8eFgjK5GGGYfZCzDDFlR73A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T09:36:25Z"
    mac: ENC[AES256_GCM,data:QH5G5+aYBSAqhXOu6xR31vmUQM7a/thIY5PeegiXsPZ0cDzYtLE6+DgZUULP/8G9d9onQu/ds7aTfYyEeyWTFCgDViq7JMck0lkGomcShKmWLL7cksTJvM9gOdnyb4jdE9HQkOPOrJgj9tIsPlTMqw2YMW8NnOUykmtjbQZsW1c=,iv:b1/6xoZXp86CsFKctXfEf6ZPWA/QU/E7p8ps8cnS6vQ=,tag:/ZoyaMki7rBLL+/BUHSqNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:78c=,iv:I3/5BJRKFDy7Y1QBU2M4NRdwuFW3LGDs383Z48m1kEo=,tag:Zyw60c8oJOtzwvHHI+ojjg==,type:str]
kind: ENC[AES256_GCM,data:TPz0CRJ8,iv:8xzqgMxcwXhjFmWySm+EQH87m5nKmVLhjmUIRrTuk3A=,tag:Gu2e8R5wf0A4Y76yB81eZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2vRDTScC+oBDLeyveikQJVs=,iv:a9VHGVX/tvTuabjAFf33mHnFUFijLV3Em/0HcyxdYF0=,tag:QbjFiOQcVVQOkF/fSg/SrQ==,type:str]
    namespace: ENC[AES256_GCM,data:BROuVf+/C8iyP8Vz0RNJ,iv:4ovvHAuQYoKL9T0Df5BCOeEEIDe5tiLoiJqiQ2BoXPo=,tag:8aYwWio43eLpYYiKLuhxhg==,type:str]
stringData:
    AUTH_TRUST_HOST: ENC[AES256_GCM,data:Lvrx+Q==,iv:t6nG9Lg/C/+Zv9lAs+28X7tgz4FQ9IkAaA+l8rA0dF4=,tag:totKwaUNMM9ZGVKn03kqDA==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:mIVxuG3c5xLIRQkH1pTshpiBBqTv3WuFZVOt,iv:VDxCpx5vzIWewSRu2ncADMJ/h4UlHwO3WCDi3WnZ+WY=,tag:jmQ2B37eLLk+HsQkvpWCUA==,type:str]
    BACKEND_URL: ENC[AES256_GCM,data:1UxMxPVkhOWqZvQGZYR3Hx4PcZKSRGVOpDfQ8QGI,iv:y2+qP79KzpDInzlx4na4F0453T0lChA0kJs0e6qKAmk=,tag:/9sq/1I+rwVDvY1cK69M9A==,type:str]
    NEXT_PUBLIC_BE_WS_URL: ENC[AES256_GCM,data:AaOjQkhpEI+GzJLtN47L8i0fbufcr+8sYQ==,iv:mr9mzH1p290yqZuTXQllHBwd2a4FE/7m8ytgiXsWP8M=,tag:E06jm14yptAD8x/vnOWGPA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:4v0EpOl7tcsoEs4JWGREQHaIl8YRrfCD5tDAW77H5pAJD+LqERkRncl8ENw=,iv:t/ixmcDsGPUI43y0Q5xKc/0u8uBWpJCIf4aI/CneNxo=,tag:m5j3Ob/VFUO7OvKzuS4ndw==,type:str]
    ZITADEL_ISSUER: ENC[AES256_GCM,data:GXQbkvYzcb/CVfbDy8NKxjOZV25ZMlATgM40,iv:ZI8OKYtAHF94DitcF9Wu8Qpw8cuqs/3S2eJjrd2NwKo=,tag:nd7g9jnH36txICnUxBWrJQ==,type:str]
    ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:tIq4yZSVv32XnuoTEOoiElHi,iv:6l/HIXRJI+w/RaO9U08mFgVHhW/UVFbTfeBzS9wGIp4=,tag:xQciS2557FlDQdeeBbAYbQ==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT2hIem43RmlSdlJnU2ln
            YWx0bEpuSEpEL3JscTE0ZFdUOTI0RmhjblJZCnBDcnJSNHg5VnFZN2pkNStuWHJH
            T0sySC85b0pkZnlUTzM4ZjRRTU9vRjQKLS0tIHhXeW50ejE2a2Y3bEU5MHdGcGtQ
            TlNhNkR3MmtyV2hhM3hCeDg0eVUrczAKnHZjIgCyoluvRjpUJQVIhlaW9idXtHle
            yQAYO5bvtjeEukq68lmHozsyVlTCHDs8eFgjK5GGGYfZCzDDFlR73A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T09:36:25Z"
    mac: ENC[AES256_GCM,data:QH5G5+aYBSAqhXOu6xR31vmUQM7a/thIY5PeegiXsPZ0cDzYtLE6+DgZUULP/8G9d9onQu/ds7aTfYyEeyWTFCgDViq7JMck0lkGomcShKmWLL7cksTJvM9gOdnyb4jdE9HQkOPOrJgj9tIsPlTMqw2YMW8NnOUykmtjbQZsW1c=,iv:b1/6xoZXp86CsFKctXfEf6ZPWA/QU/E7p8ps8cnS6vQ=,tag:/ZoyaMki7rBLL+/BUHSqNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
