apiVersion: ENC[AES256_GCM,data:GYo=,iv:fj2LzjkbQDq0n1V5NrD6VzKWbaEoHNfI0kDH1mdMsHk=,tag:zUAiVMB5cvJd8cryiASrZA==,type:str]
kind: ENC[AES256_GCM,data:XZsB9KZR,iv:nc3sbkpVOx/Oso/EvxJLWpT9E0Wo7GxHg5ybBdVJLzM=,tag:BOiyHsIbT/oicHmN0I9GBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KStM76ZkcjBxNBFkVu3dosc=,iv:jM8VootgJvy1WUXhsFEnHcV5i9QxbwksZJvARxQCA2Q=,tag:FQ/GZp+D9V48PVBsxWLItw==,type:str]
    namespace: ENC[AES256_GCM,data:YANfBA2/a+MfzAiPwx2m,iv:f50F8gg+5H/czCNXsuejLTXhYda/eZt6fj82I2vjCQA=,tag:N1UGWiejAwQyjACCVVvtWQ==,type:str]
stringData:
    APP_K8S_API_SERVER: ENC[AES256_GCM,data:VzIML9Fb9c3vfLsPoxlUSroMWaFXcisTCD8=,iv:VR6fvPm5rDWlZtBy2hbAndTBh1dDf8RaFC4Wpe3hgU8=,tag:GVertMjjw/LDy1akfpyEfA==,type:str]
    APP_K8S_TOKEN: ENC[AES256_GCM,data:cjfLKn88Oz0jzIaln7RtlnJ7v7imS8ykL1c8hsu01PYNPnefGgRQYj7sr1v52W+XQhMbTWz/4ZjkKpngSv8IOxDlgQCFBXdwEa7p07pLQJivGrUf930L+Dn4fzj9pYHlIVv2u+zJQaNOGf4sE5uloUx/kUx6kJQLWRr9n8XduyRxyhO0E9E+Ig27cQ9f2YgZ5s5NsaXvw4a1jc9Ut30691OCRfrqpoyrj9JFy0RJSLEyHwljl7woiEo6Sh/VHC8aSlqiN7tEkW+hNmYAxKEYKjEFXnf9Fy5lttoZ5SrgtWKOnlFD/z/yyOOlFlOqivt2weylwq2YX5zWDLk+NR37ycB8WylQW+HpNfHz9jmYWjG9OxCMxiNgGWx7xUd1bP58D9DlY/Zv0ZEdP8XV+8CzPWH3tNXTtP5bskGWqDMWMq8aFEOHO6VQHzZyZIIFei78Okc0wO10nXb96QuDDD7OL2ZBkiZwDH35XAWXLPnHC3GEInFcxeyZL799aYRqSqnascyMq9Hjl+y5xvo30EuUCklpoSPcRAidMeJUPd9NYNkf+BcYHzPwFvLoBSBXmjZzNnCG1oa5XVoh5LVPK6img3mH+7ve/XV5ArDhojTqmQ67ND9W+ifck3kJwuSkfT7XnHtM4AawYVi+Mj638/39/zlPpHy4S9eafW8CV8dIv9uLFQLEfQq/YjVMgbiwaCSxEP5wcClJ3GrijY3uFiogv/yH8Psrofdv48xgOLQ+a/0qZJbZmNGyumxhS8V2ZB7ZN8qD6O3gbbAB0jil89nm1i0DToCe+6qye+WCcg+roMFtp/tDZPWlLIWWjLlPpEkiWKkybVgMzcOMYEzmJSLIACUQmaRODcpHOZSeQkNXYPb0tGIjCHJt4af7ZtakwTV7o5a0uawx69aFW8THdF4FQ0q+YDDPESi600S94VIJgFZp4L3SHps534LTl0NYeIt7i7RxQEOZzUACz/gjzbv7oy5OBzb2SzeFldO4WRHG5yvqZbqXqOBfVLjysd7JLbGCU1reDisFfEg9emiKgrAxWTBW3vAWWWW4PMi1WeWYIw+5f/+fX6Hr/sg0PBrc2dhfl78fxF94IaBwhQiCeDvTa1bZMsV5e73owxMYiWQT0sGk9GZwpbDbzVIP8ilc37IKjqVcE6TUhHl5K7P/I6aUn1ceeIKyl9sDDhgXmYZnHtQIRT15ZuIHRilxbBbxVW2iUswmgo0rgcNSd4LKj6wXPK7cXfCR3T3oI3JDPsH/,iv:MqGNGFilfevSxTqKC+MT7+AB9Cp20LCLccZsZO5Hbv8=,tag:c50tM5w1AlHRDnf/g548Wg==,type:str]
    APP_K8S_TRUST_CERTS: ENC[AES256_GCM,data:z1UwJQ==,iv:IWI6GI5ujdl8W6SGL03OgX8rv2KWzh0RjlZ/LvA2QFk=,tag:FcMR0AfGw9iYx7cpd6Iglg==,type:str]
    APP_CONFIG_ENCRYPTION_KEY: ""
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:CXV0D4nX4h0dgaIcoeZ65MbXfsJFw0P24OrG/jZVd5S9NA7r1pBHDfNHIqDRJQqGypKWksmFxsNF,iv:EafznwSMNG0TPdemRsYRq1M6vHxq0Xg+wcr2XPeYUT4=,tag:rwzU3iqmI6AMR9lihYBp4Q==,type:str]
    SPRING_DATASOURCE_DRIVER: ENC[AES256_GCM,data:rAGJw2VzDcKJYtkn4ZojKhVWKc6Z,iv:GSntWTFI39sB6gUlWIa5yZRU+UigNhTgmjjfWNs8cao=,tag:+RtVQeKTUTodFtdDRroygw==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:RQkxuEPcqg==,iv:lHb4DhDPzgKpEJ5H+k5W2RE8PzX6TRkArhdmGD0CxoE=,tag:qtPL9jrzZ+A2vmO5r6yfdQ==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:0sVgYu+tueEpPfLW,iv:g1dgpokywDY2Z0PT5kvLjCQcot9zZyAy+hxBFZj3oZU=,tag:ImxanZ+4AyJljnwgaboPxA==,type:str]
    SPRING_JPA_DIALECT: ENC[AES256_GCM,data:YCsg9ntmDPqTKJZsx+KYAj+a+CCbxSa5FDTjJwxJ7FcshdNLbguu,iv:v/kKuKb1f+d1ttKaWmcKjWFMVGHzLm3iXv6Xoj0ObwE=,tag:qRhVoqpddWmuYZy0C852Xw==,type:str]
    SPRING_JPA_HIBERNATE_DDL_AUTO: ENC[AES256_GCM,data:N3HdeGSX,iv:kNkznm9l5COd8cSu5R0aQo2YyUICcY5JH3hwv7MFHgE=,tag:br5i4al7RkMZKRyAcUZn1Q==,type:str]
    SPRING_JPA_SHOW_SQL: ENC[AES256_GCM,data:WFsR/Og=,iv:m9/xSOnEvpj0IZxOpXCXmcX4Div5AQS4N9l6+0mMrW8=,tag:/uZd0yWrutWVFYxrGPUkDA==,type:str]
    APP_AI_ENABLED: ENC[AES256_GCM,data:jCkf35E=,iv:0jE8R6SjUTx3xqi3gSiJqGLk1LAJNPjTJKK8xgk43WU=,tag:3mGhpJVwGD1dH6KGy3bM1g==,type:str]
    SPRING_AI_OPENAI_API_KEY: ""
    #ENC[AES256_GCM,data:q9MR9JZBCv9q3kT2qyaXzXrF8xJEX9fzPN7eRoShMpljXB12DU/rt2f4EdE3HWmwI2Q=,iv:nLBGmt8aYkWij1YEtngRTU1J+gqKPaq/1csBS2+iL4s=,tag:tZuMYpwIuKKvPGCog11wjA==,type:comment]
    #ENC[AES256_GCM,data:vYWhzpgL1XAKlcOoSvlh+Gg20x6Sn6ON9yAZJxam4LBh7Ze/PWBpjg==,iv:ft4iFbS240wQzyyuj3nSRQTmej+Lv6SMMRZLhsobuHQ=,tag:3Y9gPbp9z8dyOc0X+LjLlQ==,type:comment]
    #ENC[AES256_GCM,data:mV8OINnmM4LG+JLjkxO1STIGSk50rOK+rav2Ef1Suipan6R/Fw==,iv:Mmj3NCRT6SiJJtXHpS8Btcspom0wL73oLtu54S664Dw=,tag:1NdMLFK6a9UwWU7n5sOzBA==,type:comment]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGFPMzkyVldTUlh2UUZG
            S2lSRDJCQkxVdWxKY3dtU0Y0enBGanNhenlvCkdsSllWbWFubUdCa0YvQmpLcDhI
            ZzBkd2RuYXcxOHlGdWdvcjUzOFlmL0kKLS0tIGV4WU04MlRDZU1lRjVvZzRGeUtn
            MEhiZ215MklNRmNpTE5WUlFjS0JKamsKh1yk10sHRPBHhHlBbSu3VM8JamOH9/MV
            ZnKgssamT6UjOwUuz/UvBf9Lupu1VvyrESrExbgsRnaxBtV3JhlVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:13:08Z"
    mac: ENC[AES256_GCM,data:62HMTa7SIIrZofew8kVbs1wWMNpdd+tUPHQ17yfFgEzUxBt43pVULwxVkSoD2flYcE1lP+8LrVl8ChJurceeQd6HPusY48oXpGWLGAqpqlW24lGgFvLyR6YGeDK+fTA/1H0YgrT62XjF4w27+i6Tkz70thioJw3nRGiyvko8I64=,iv:2dweAGXAOt5qgxafZPoOVZ4rUyjevveD1t+5klAd2/c=,tag:bqcmaMO8ule1rLgRwaE4/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:IRo=,iv:Y4QG8bj4pcljmNtx1rO0NQBQC129sV1lqoeI9ROYdK0=,tag:nfTDg7XlVAQ0mRe67BQ79A==,type:str]
kind: ENC[AES256_GCM,data:PSBaIhDV,iv:2pu4P5t2ezoENXlc7sJ5RQ9OOsyU02JHCQp34AIQsIA=,tag:DOh32sXyGf/Uy9loDAk1yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X84TREaTKMt2Dy3gMBkUtLw=,iv:9kMjdRu3dHBYBoLM3dxtRQvf01cIll9VEwDCNu/1QUs=,tag:nuP2CrZZ6mw7vk89GXnvWw==,type:str]
    namespace: ENC[AES256_GCM,data:T9ld4I5OZCFns+cRjwVP,iv:upEHF6pKoR+LQigKwL7l7gS5fAZkhIBOa1JCGLg+R1w=,tag:lDtBHXy+pjoOfCvu3QYvQg==,type:str]
stringData:
    AUTH_TRUST_HOST: ENC[AES256_GCM,data:TvjNCw==,iv:unOwKpFFWAlss+bZArsdgMWKVP45SK/+IWm3BpHiyCM=,tag:762YcdQB9DJGQHnH4XW06Q==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:nL5ILWhJuhE1wFryXThD1KXSRQgd12Nmuqb0,iv:7yabDK2WQMqPRAVNeXdlQkmp6xoVn+iSzVgiUkNH68s=,tag:lbGQiEdTaxmU5rMPVOfjrQ==,type:str]
    BACKEND_URL: ENC[AES256_GCM,data:FbJ0oxtD3Myhj0MvFPHPiVMIrujimjB3oHFTapMj,iv:WiLanC2kgaSljefG7g2KUAcRa8QxymC9yiDVXHNNmGE=,tag:5mWYIZbgRkHnBpyWMfnghQ==,type:str]
    NEXT_PUBLIC_BE_WS_URL: ENC[AES256_GCM,data:S/4anfah29awhjuM6zvayvA1A6HvC2zo5A==,iv:+LgUqCPbsZTK5JO++sffvZ2ADoBXxq9WW/W3MVHqQWg=,tag:I0cMn3AQQPcC9LgjqoI+aw==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:5NT39nQn1HKyF9XvM4Ie7bJAZhPtYXP3LOE0z1ZJZXTMLYSo+jnKLY4GKm0=,iv:JU1fnEvbsVXLUMqmNdXgrNlEwexD9YSX56IK7VI92yE=,tag:c+ioLqPabUh6sjLEWSg1ag==,type:str]
    ZITADEL_ISSUER: ENC[AES256_GCM,data:cQqk+vDgzR327tdXECmfAS2CigHoP6nj36oC,iv:PqH8tUSQh6zkh1mC/cAVyXrHC2GhhINHgkXm5P743B0=,tag:KDhp608VHFwAXwUGdJoAQA==,type:str]
    ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:eF5idVEiSmiWjzwW+L75dCls,iv:43o27lqfdCKOe+3l0slM7ezgFLigO6TZ2Q/Cthz20dc=,tag:2iB2U/AXR84LJY0i9kDsnw==,type:str]
    ZITADEL_ORG_ID: ENC[AES256_GCM,data:m4bGFjduLmMJC7OwmzgnKutW,iv:Ypgdi5xKu5YWq+dRTkjSaDPXItvjkWMAQmBKkvlPCZE=,tag:6XcZPgDGyOR+ieZQQoGMjg==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGFPMzkyVldTUlh2UUZG
            S2lSRDJCQkxVdWxKY3dtU0Y0enBGanNhenlvCkdsSllWbWFubUdCa0YvQmpLcDhI
            ZzBkd2RuYXcxOHlGdWdvcjUzOFlmL0kKLS0tIGV4WU04MlRDZU1lRjVvZzRGeUtn
            MEhiZ215MklNRmNpTE5WUlFjS0JKamsKh1yk10sHRPBHhHlBbSu3VM8JamOH9/MV
            ZnKgssamT6UjOwUuz/UvBf9Lupu1VvyrESrExbgsRnaxBtV3JhlVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:13:08Z"
    mac: ENC[AES256_GCM,data:62HMTa7SIIrZofew8kVbs1wWMNpdd+tUPHQ17yfFgEzUxBt43pVULwxVkSoD2flYcE1lP+8LrVl8ChJurceeQd6HPusY48oXpGWLGAqpqlW24lGgFvLyR6YGeDK+fTA/1H0YgrT62XjF4w27+i6Tkz70thioJw3nRGiyvko8I64=,iv:2dweAGXAOt5qgxafZPoOVZ4rUyjevveD1t+5klAd2/c=,tag:bqcmaMO8ule1rLgRwaE4/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:j74=,iv:HpzzfoOLoUGXBFpPzal/qKvMbcazsS8ZMmmG3vInm+c=,tag:ZsXawDUy+bfL07YBgWB37A==,type:str]
kind: ENC[AES256_GCM,data:5fXRsFg7,iv:1iXvzM+Sln+SvGcm1e6au/llP1wlhRse/ey0uJ5zDnM=,tag:iZgOnjGZi42qGr9NhKVrQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hNsPcbmA3vY4CB9Fe75gBk01YsVj3b2bkg==,iv:HLHgf4eaOe40fqd3aoyDdiJ0ebdky5Wl7F54QK6ro3k=,tag:ml2KQim4tIeiZDAQ2T90RQ==,type:str]
    namespace: ENC[AES256_GCM,data:8GBzX80sL3jeZRdorRNY,iv:t0+FkhYVNQRaa1BzSoB8Z5UXUeDPf+bl2GG4o4gsUBk=,tag:EpEmgJtrptyyZPtqH6bP+g==,type:str]
stringData:
    postgresql-values.yaml: ENC[AES256_GCM,data:IyGnnCpztX8jxjI544p17ySXdbD5BEU8mksraD8NVqXmAIMpNx/QxAE1OaxgLYql62NAoNqyF5ZtMLmL0XIKq5+v2DQ5tadt,iv:jsqYtD591CDHB3UrtxGXDJXLYC3+65QHNIDv/QJCdhY=,tag:Tjs2it+xI8uQEj3mnwGhbg==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGFPMzkyVldTUlh2UUZG
            S2lSRDJCQkxVdWxKY3dtU0Y0enBGanNhenlvCkdsSllWbWFubUdCa0YvQmpLcDhI
            ZzBkd2RuYXcxOHlGdWdvcjUzOFlmL0kKLS0tIGV4WU04MlRDZU1lRjVvZzRGeUtn
            MEhiZ215MklNRmNpTE5WUlFjS0JKamsKh1yk10sHRPBHhHlBbSu3VM8JamOH9/MV
            ZnKgssamT6UjOwUuz/UvBf9Lupu1VvyrESrExbgsRnaxBtV3JhlVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:13:08Z"
    mac: ENC[AES256_GCM,data:62HMTa7SIIrZofew8kVbs1wWMNpdd+tUPHQ17yfFgEzUxBt43pVULwxVkSoD2flYcE1lP+8LrVl8ChJurceeQd6HPusY48oXpGWLGAqpqlW24lGgFvLyR6YGeDK+fTA/1H0YgrT62XjF4w27+i6Tkz70thioJw3nRGiyvko8I64=,iv:2dweAGXAOt5qgxafZPoOVZ4rUyjevveD1t+5klAd2/c=,tag:bqcmaMO8ule1rLgRwaE4/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
