apiVersion: ENC[AES256_GCM,data:vGg=,iv:/tenluCVGW+0xUgbbQC0/zKG2UxoB34Z/KrH3ZFa2VY=,tag:KjFgxbPXGEqZpEH2Qag/vg==,type:str]
kind: ENC[AES256_GCM,data:bBaxrb84,iv:DmU0ma6ycRlQbJq3ivxVs3iH5MeMaN80hhNKGLXnX8A=,tag:SjrKtdINE7XsDp3mQ+1xWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+HF2D5kAC9uRpgHwZ9+06H7mfTDCJzQ=,iv:DzDln5qQZcq2rDM8peWILQnmeplor45I2STJNAEnjug=,tag:lbHCcCb+Rz0qT9u6eq/VHw==,type:str]
    namespace: ENC[AES256_GCM,data:tokyZa7dTrqv9DVznryc,iv:3wYSm7paexWmsY61zpqG9Wqj80zxbdQre2/tqtUjU/4=,tag:q/EsZJXss0HYaPJ89m/D/w==,type:str]
stringData:
    APP_K8S_API_SERVER: ENC[AES256_GCM,data:u+U8bMsRrggsOPY7hQpG0j/WPTzjODfoSWU=,iv:tIYe+RriS9JaiAlGmVrAzPl1Sr/pE30iir49Es0aJ+s=,tag:tupg/5kO4k1+WYKInaeIRA==,type:str]
    APP_K8S_TOKEN: ENC[AES256_GCM,data:+85X+SUtv1wUAC3rQGwTWMr+J57cgc+Ac59oa28mbnw9bK1bXPC0s2t+tg2AxHgPj6aPUl29/nSjUyxpXJrxklHG/gHdLsrxG1T/Gls3x890yDXuNGBBGMgDcBiyqVAVg6O8iKe9OgkVmGK/iALLZfCeggnuqXzvI/vN2OKVcBIx2vyAd2Ki9GGgE2ZiIIukqt+idqlVqH2R16nPmme9oW5Ty1n4ebHWCElOrpD49ocsVeaQkJRaG9KCFmj83kgK8ijngygeqJZKRzHmXEsaE7OxZJersfwT5atfLKSeGqHwFGhG2rVSM9hnccVUROnIXsnmGghC37t5W+Q2oZ2F8HIqbh/yNLw6Egju7xO78HUqjLzCbrkTNvVvS7qY0kaLHSoImIF3mjsZk1YoWrxbrD3dZK2pbnqLXQjWsm4cD1EddmjfNv/qHaiF5XeJzUr1uiIQM+2MrAdNun2FN7eJaculJaDTvh9+uHnpPUYL7wyWMuu8fqJZpYw5nNCGBGm6CJ1EQWSKbnLnD6I86OxWoqK+R8QpAi9ZQZzw2E2Imz5DrZt5EuVrlwV8iCVOPpEUUElYo/aNTy2j7L7mtam3tWRUnrxsgnFqCqgj0g21uGZR4WlL9RFzHDa98y5ziGFJSgAb8qZ8rjdHe0/FBGKiDDdYoPQCzEzqUK5zGSiZfIEJri4RNHubbWk6GuOtIAPqJ9NLieiHlITlC+IhtUWPCmvECtbKlPQ4Tmr8GiR65Qv5yYm4+wo3ZLim1DxQnSxNxDZL1+zXUpAn3vRgEbQ5h93FMglpVYTtPBpAwbB1DqgGZ4N7gBPht+emMRLNsPk3aif4kW4Z3z8NiDK1VRHME2RcZq8jsx6SY7p6qkRBAgJSe2vU5Krqii6tzjMSMAyZbtyJ96i7ZVEpeAiUJDW5axITBEO9r/VwtIhxFJtb/IF/AW38xezF8iDQwhtN7qwt/oxmMA66+6wrKR+/2i2CoWNH0Q0wxgCfIlyfcmGPfTwsErLMRMf03Lo7oClgm3S2tXvSFFu10Nd2/rftiEwFrWZUJxiztIbuHTKMQWXNPV8u944uURSKnL1JEo6dNT+0YW6h2688iCzc+FXERzx9ZEWhl5bM+eTpisv+seYNJ7oH9NJpib2BrnxPDnMZJmDVpbcKEBN3uAUPkUJCYfWSETPJihxf1iPOnjW1zaLYB48MmDbD49gtNDG7Gv0gFYYce3Zqv9omPbR+q3hR0nwoqzYtvNNWmJfecPEC/Sxe,iv:BUNj5Y3SF3dUfGx+WB6/6bsmNASnw5ogFK1U8ehldYQ=,tag:nw4hD+RfPajOoao0udeBJw==,type:str]
    APP_K8S_TRUST_CERTS: ENC[AES256_GCM,data:PtpNNQ==,iv:cZK78aBVxnoW5ZJgXNpBHHa23UPxDx/eL+wZhh47C8s=,tag:RYR6963ZMfdstevqc+8JCA==,type:str]
    APP_CONFIG_ENCRYPTION_KEY: ""
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:+FjzoSHO9eTZQWP0TvvRFo2998MGoSXlEIFMB14i6X3wUWAnShR9rdfHZ3VWC0XY9yCUHz4f2cwd,iv:8Cypg2WCpWwEl1MCIJkr3bGylAW0mnDssqhZvQqrSkw=,tag:c4IIZ0FGeHdW1lbiPU/mfQ==,type:str]
    SPRING_DATASOURCE_DRIVER: ENC[AES256_GCM,data:eJzu4dVa27TpUBySbF96EZCUBxLz,iv:XzacpzXu0M7FOT/6A4YYRhHilQEr/BU4LVNCbgg7U+o=,tag:b003Pfqvk9Sh869ertP0IA==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:w03AI2/eXA==,iv:kyn7f58f6lT9k/IyX1k444vXK00NuVboRyb0l6kxTbY=,tag:z9HEICRAAmVRNL825Il0yg==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:tKqmlWErmrbgQESK,iv:lTRmr6FkPNjUFrpruDuvJ7iEk3TLlN5ODNh8nv+rOMo=,tag:DZTjLvViCfESHt0VsOJqxA==,type:str]
    SPRING_JPA_DIALECT: ENC[AES256_GCM,data:/43tM5NnO2z6XpooNkcEpLpGzS+sxbtjNdHX1t4bpv/aZ/yDGK+m,iv:IBAZFP9hA+CYGw8B9R7oMIcubeQtG+YdtvmBuk07yFs=,tag:TZ/t6+80U54Afoj9ARDGbg==,type:str]
    SPRING_JPA_HIBERNATE_DDL_AUTO: ENC[AES256_GCM,data:OnSEKaKU,iv:QfpS26E/oe4/+YclpU8//GkuEhF9Jx3yUe8KPH1B+2U=,tag:pu7hfxGGDOgV56z1ww5Aaw==,type:str]
    SPRING_JPA_SHOW_SQL: ENC[AES256_GCM,data:0pKWdJ0=,iv:3FGxi7GEWAFCKgPaseS+Z8qRtEJSMXrZ8gtjdBm3bLE=,tag:H28DNDD7vMEY+LySX93S6Q==,type:str]
    APP_AI_ENABLED: ENC[AES256_GCM,data:CjCgBqQ=,iv:KTsdi4sCByZFpjuUQQyk//2CPWw1X3rZZmRydqQZMwE=,tag:XrV0xqL7j1BfFwGbq5RLOA==,type:str]
    SPRING_AI_OPENAI_API_KEY: ""
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaWMxQUtUSjlBMlJzTTQy
            WHNYdzhpb093Y25ZTS9MQ3hacmQxdkd3cGlNClo3Q1V1a2xXbEh6YjVMNEk0WUs0
            MGphdWoyUUJGbEd1eGlxOGlIZHpiM3MKLS0tIDNXQmlVQ293SnZEUjlUclBDb0Z5
            bk8rck93U3dSdWNDQzlOZ1RkbEJUYWsKjo9VpdZtHG1ZDWW8b7JFQiSd/BLHJEnL
            7cin3x2+aGqVb7HWk1zBl0CqQb9lTJiuAxMe7Fv6uFHvfJPpoZhfkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T04:19:49Z"
    mac: ENC[AES256_GCM,data:sdVE6Md+VzPm1y91U+KtE5Z0FhOX5xgV5R1VcsV/FdyxloI8HtGNFYxmYWZ0lDiaD5pt6cIxk6rBu8UV0e7ctdNjQMcjDyow3jTqIyhXGsLHOI8Y23ohqCJZ0gVO1YWeXT0+zxoMPMN1SNBbVDDTkzXLo+j4JrqL6Az0dxrlgKQ=,iv:NpCGTVCkM/xXCA3OlnALsAIS6fxOXNjbaUFHLiXmry8=,tag:yD0rYM0DviQjBUKLFm2f2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:YZI=,iv:7r5jyeb9P0Wc+gCEY4ErwL9AArRtzT3R/GgtF4iYr7I=,tag:cWaGkUEk28yDpQxwS3RApg==,type:str]
kind: ENC[AES256_GCM,data:e6g5TuuF,iv:LKVZt2DvorBBhDIr1X3foJqo6JnzDo/WJFe29+5nDCU=,tag:GLUnME35ny28wXEEUl/vlQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:suVPSfNjmBrT5z9lMND9yCwTgg/PgXk=,iv:a9SOkLqNPZ+3qetLqMOUuU+6LSOk6W+u+C1AVNPPNI8=,tag:fVXxl0vJkIlq6RYlNf1Hxg==,type:str]
    namespace: ENC[AES256_GCM,data:h1oUcyFYSxahRgyKFfkN,iv:wQqc55VyBr7xwb+XXuYhHB87AUU0eCDo3Zk9y4S8odY=,tag:b5TSAxOXkIDANOMcwGhQiQ==,type:str]
stringData:
    AUTH_TRUST_HOST: ENC[AES256_GCM,data:6KnN8Q==,iv:kQ6P0gi6tjNV1/lUiXahC74NIhfzO60KHXr4/QbP/eA=,tag:aY4/vFR/RjCM4cA613Mr7A==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:MIJ1TGoV810LFOLd8nOcKZnGA8R20tUPPA==,iv:tW/w/aDKGh/SZcPiksui+f/7qzakti3ouKa2rnQsFBw=,tag:BwzhDNr+MHc5GOR5nRUdhQ==,type:str]
    BACKEND_URL: ENC[AES256_GCM,data:qqRwLwAvWIlEfDpRakFgctzPM2oequKBi7qDMM6Rm/Y/m/fE,iv:tKAGc6eBouFtZVWPrUTwfvWWTWhxGx/C0Ubwmrqd+jk=,tag:/gbHuvoUUo2NxqMq4qAnww==,type:str]
    NEXT_PUBLIC_BE_WS_URL: ENC[AES256_GCM,data:b3HRNIVwqm7l/WKL/nCXSDGy4X/2JPQ=,iv:GERVfjt5Fn+hkyyczhuw5i9Okl1ExIdGdsM2oQiT4sM=,tag:4vOmf1OiDYurJghtYKA3lA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:XaQaJHvlU9VrJT3Z/q+RoapwhNILsEwuWNf/nJP2gfWiqQiLSZMetVDdtH4=,iv:cxVzs+zsiSOspUZ1/LhKYYWhraQ9hipil+sI2kX1R18=,tag:9C1inetmM92GQXoZbnoLvQ==,type:str]
    ZITADEL_ISSUER: ENC[AES256_GCM,data:9ayh/yCfmnenF6imSkZ/NctrGsT3mxi3VQ==,iv:TPxQmyjr8BY9YEiSiLYLso5zn03pf7X4m3CZaSTeYIk=,tag:6lPhNbdhVhlpmJVPB+m+vg==,type:str]
    ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:LhHyCqyJDcZoAioLVAdoA8O3,iv:Kw5bAYilkcAT7jaZHHy7Jj5tFZIWTUkoUBdPpqptXn0=,tag:Lrv2i34asTQ+v5/YVmJeQw==,type:str]
    ZITADEL_ORG_ID: ENC[AES256_GCM,data:f4D0IAQRpb/Bmjy4swuNuUbt,iv:GFxXo0CdnCooio/uNZ48qea05W99+Ds5EjJtRixjI4U=,tag:G9ctG3YcIvoPiWczCaBWKw==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaWMxQUtUSjlBMlJzTTQy
            WHNYdzhpb093Y25ZTS9MQ3hacmQxdkd3cGlNClo3Q1V1a2xXbEh6YjVMNEk0WUs0
            MGphdWoyUUJGbEd1eGlxOGlIZHpiM3MKLS0tIDNXQmlVQ293SnZEUjlUclBDb0Z5
            bk8rck93U3dSdWNDQzlOZ1RkbEJUYWsKjo9VpdZtHG1ZDWW8b7JFQiSd/BLHJEnL
            7cin3x2+aGqVb7HWk1zBl0CqQb9lTJiuAxMe7Fv6uFHvfJPpoZhfkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T04:19:49Z"
    mac: ENC[AES256_GCM,data:sdVE6Md+VzPm1y91U+KtE5Z0FhOX5xgV5R1VcsV/FdyxloI8HtGNFYxmYWZ0lDiaD5pt6cIxk6rBu8UV0e7ctdNjQMcjDyow3jTqIyhXGsLHOI8Y23ohqCJZ0gVO1YWeXT0+zxoMPMN1SNBbVDDTkzXLo+j4JrqL6Az0dxrlgKQ=,iv:NpCGTVCkM/xXCA3OlnALsAIS6fxOXNjbaUFHLiXmry8=,tag:yD0rYM0DviQjBUKLFm2f2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:BME=,iv:E5neShQ4WlJCKo2yVN9bcCyLRRK7ZkvMKV8la3AX8SM=,tag:QL4dAeCAuw4G4b0Rs7dGoQ==,type:str]
kind: ENC[AES256_GCM,data:V7hEy6Ei,iv:s5dUeCAhBQiYA23WSZzHBCtVgJIcuZdGTSFqd5V/c5Y=,tag:An/6XTR18ALbzn6jo6sstw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XEwglnBrbwpWpiZhmuaQUrRJL+hdEKNOCA==,iv:zoz56+NliRQt/kG7JY51vJKfMng6t8g1i06iMC9+oK4=,tag:4JTpc7driD6k5T4RwtEpvQ==,type:str]
    namespace: ENC[AES256_GCM,data:vjPoUOSkYP3m9KpeagZ9,iv:rfqaxVIF+72NfadDG2fYVTeFqhqdmJDVNAiBxZzxpZU=,tag:YV5I0bkWqwqB/El8gw+lQA==,type:str]
stringData:
    postgresql-values.yaml: ENC[AES256_GCM,data:Sd24/l0A3UGpLwjbKOsw0toliwOWJiToVLZsYmJUp3MhzVi+iO49DiMtl7l9k8VfH8qY7WGR1K0Bwrh+TDyOHHAhSAprVTJ3,iv:lmyAp/mpw9gdO6edtT/iLLi4L/sCyFTE7eEkmIdYpZc=,tag:6sj0qxRueYy/1g6VHDvh7w==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaWMxQUtUSjlBMlJzTTQy
            WHNYdzhpb093Y25ZTS9MQ3hacmQxdkd3cGlNClo3Q1V1a2xXbEh6YjVMNEk0WUs0
            MGphdWoyUUJGbEd1eGlxOGlIZHpiM3MKLS0tIDNXQmlVQ293SnZEUjlUclBDb0Z5
            bk8rck93U3dSdWNDQzlOZ1RkbEJUYWsKjo9VpdZtHG1ZDWW8b7JFQiSd/BLHJEnL
            7cin3x2+aGqVb7HWk1zBl0CqQb9lTJiuAxMe7Fv6uFHvfJPpoZhfkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T04:19:49Z"
    mac: ENC[AES256_GCM,data:sdVE6Md+VzPm1y91U+KtE5Z0FhOX5xgV5R1VcsV/FdyxloI8HtGNFYxmYWZ0lDiaD5pt6cIxk6rBu8UV0e7ctdNjQMcjDyow3jTqIyhXGsLHOI8Y23ohqCJZ0gVO1YWeXT0+zxoMPMN1SNBbVDDTkzXLo+j4JrqL6Az0dxrlgKQ=,iv:NpCGTVCkM/xXCA3OlnALsAIS6fxOXNjbaUFHLiXmry8=,tag:yD0rYM0DviQjBUKLFm2f2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
