apiVersion: ENC[AES256_GCM,data:m8o=,iv:niOICD+odcfVTL0Gdv0MM0Z5HoW1S7jxiygkYrHOTIo=,tag:Y2qtKu8YHrl7lK/nlMyuaQ==,type:str]
kind: ENC[AES256_GCM,data:pNjcmitE,iv:20DYFZKFIX03TMJX/0/mHKSfdE1SDXodVuvBOmRdKa0=,tag:qDUbgeZl61xm7a3+Qsd44g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+AJUesUdAh3YIN2im9kJ18c=,iv:CthGPqV93yDlxz3Bc8RaHFQNKfhel3V+7ltzpjTu88I=,tag:tOPfCgAZcZdHC9vwnAMpeg==,type:str]
    namespace: ENC[AES256_GCM,data:QJB5c6LdI2Px287ek7pN,iv:qPySVdeDwtkvv/Jo2Oz/XiPFsca0vmSFzvxcJGpx1As=,tag:gyZTL2YMDWrwvph33jQGzQ==,type:str]
stringData:
    APP_K8S_API_SERVER: ENC[AES256_GCM,data:o8pYg+xogNvghXcbDyIe53CDkLXQSASOkws=,iv:5hBzyAd+2JDj1x7oW1vHWZHULSQkwlpboAFYeZfbO6k=,tag:5G3fZvnd4JQ5Ocw0HLZd8A==,type:str]
    APP_K8S_TOKEN: ENC[AES256_GCM,data:y7bv3i8S05wgLjkttYyS6tZs8qDCRGK0n3KB9tasSpwW9VgAxdxMcGvvBJlzHZFK5RVmDJhHZcr6uUhiyh2ImAGkPgkfegzO4AbMQ2iyujvBhkMQtLktS2wU/tCYEhVYnZiRB7WWUBHIH7CgJYQvak1yzugI84m/T7LM2N5dpqHVXmoMJSgcsjqThOBbNLjR+hFA8LemTpEQDGEsdL1VpiRhHrN/M8lu3O5rR1Kp90FoMCS+oQ9YAiZqFXWsNiZzpaBjFrgup0KrI8pG2ZAz6x55yH/06Eo+X+FN9AbVaaaXgBmRCQxmzTzNwEYLC/v2lXchBJUrzn1XstVyppFshoRUVF9zJnKej6kiuMTzZXDVZ89PTJz5i8Ke1fndHNJlKKe2rAEpLUTGDLTZZTN2PiVmupYl8cV7GN3HIIYsnwaA4rd5tWzwQjJSn29cA+HwEQqOYRASf/IIav2f6B+s6LIaIQEj7B40mBO/s2R4/xfch8Xv53GekustkEzCEVszh1TQWOxNeQ4g9FaNfF6z3/LtvW13Vr7tIDk+9r+01IUDgKmOBqBbWMABCqzWxdeDBXgC87r0N1RLAnswR/sz0GZbifqTt+klYSSLNUiqSQz02baEr7cIspEBrqgEw3a654OjFuniX3kLiQaQSrXWkdIH3aKsfiNMJ3fbYVvvM5FwQ8PiPxla+7oTU4KAOcJ0qbUkQQyLZKImizLQYNTtx1dsMbW3jcRoHbC1TfMmMKB3+WsaZo6BKNiOzVS1BfPQ6Umj4+JzfJznczQZhr7dZ0bCyf9YrZrgeAuuZqwTHQ306xfEgfyoj61TcWXnPXv51AQ+WGG1Pfqoc7recjpLgFAcGuggw6OwrtCariVUZVn35H9QDkhliMwgZoRYOptDnITCG7h2N/z6Ut+5fWG6G6LAunsNyYuXSQJAe665m1EHBCzs+TLi3D0vDNaKbaQQ2kzD93fumN5F7IstU5/GwlgcqQaST9iFqXLE9/cl7xlx6V9fQxbAoWu1v/O6OGwUe+tl5wGsImxPRiCNwcjcAHWa2/lanTCl3+HldM8GVY3K62DSl4opLqLxHiJ0QDNh/gI6Kqq6TDiQlmlUSklQxbph/Iv35GcEkKBfoJT6GUFdgb17SkxWjs9fvbWIfqd/vtLxc/WKCM1THkjhOusP3VSmv9yQf+HO5Lsk6Ow7HlxEZRQfgeGvTZ+GtunGfINjo0jAPKaSA9IDcl3wB3UUJO8BZDGsSHe3z5KVgRzQ,iv:38WVzkDjJJrLGSqCdRmFuPJCSTHy3AuV64x8smW4Q+I=,tag:+IvBtZGULSpoD0cCBeLuCw==,type:str]
    APP_K8S_TRUST_CERTS: ENC[AES256_GCM,data:1nLwcA==,iv:BGkK9l4oHojdSxTCkTQMYV3zBusEpvv8vb/sYPYwTeA=,tag:BvB/tEAzc0qDYehS1jTE7A==,type:str]
    APP_CONFIG_ENCRYPTION_KEY: ""
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:LoGZCI2r5N40tAxeb6TATJVZOnsJvjoVy+koess9fJR2s/6JAEnDB3h+o4tJ/OcGyl1U1pTf4vwY2DNhaVs=,iv:EgpGupaltVpjE+zGj323z9GIVtB8yxnRJaZT1Cw8aGs=,tag:4OxE3zl9s9NS+0dD+rQZwg==,type:str]
    SPRING_DATASOURCE_DRIVER: ENC[AES256_GCM,data:inGm+Yi7WhPO3lnjDcfv,iv:YaP2gvnj8J8aBhkT5316hQxImMBHoXiiRJeUeRHik/o=,tag:wqoBI2761tJEx7Xuo4RmwA==,type:str]
    SPRING_JPA_DIALECT: ENC[AES256_GCM,data:ZEIwluOR0NKtU/cJqGt7h29fwhGOqZJZBIzOsGxZUdGrgp77ZgyWA86W6jnJ,iv:2tzp23dyVX4fffTSpBcRoAUHBpMittxe90IuUNriyNg=,tag:NVqHwu0dLwoj8oGatNZ2pw==,type:str]
    SPRING_JPA_HIBERNATE_DDL_AUTO: ENC[AES256_GCM,data:UhQkI/ME,iv:l4sNMipXYzpLUsWWuUDxmFVwDssNL9BHDSKGGfN5wGk=,tag:o3w24+tlG4NO6/19JEQxqw==,type:str]
    SPRING_JPA_SHOW_SQL: ENC[AES256_GCM,data:RDAepBU=,iv:esYarv+xF7c2zIXM3a1BTVawrH2JhPqT3idf1nVRFNc=,tag:kH6wBJCwJDa54Cd0iejuxw==,type:str]
    APP_AI_ENABLED: ENC[AES256_GCM,data:BvAyjeo=,iv:/ak/4MWfK6W7L4Ep1k0WC3UuXDBz/QgrT0sQJmMvEuY=,tag:q3ydz9m3Cu48pjLJR4ZKmw==,type:str]
    SPRING_AI_OPENAI_API_KEY: ""
    #ENC[AES256_GCM,data:i2F7KBcAfZ4jLzGfWenf/OhAma/9qcmxcWjEfmv0b0a6Q4cRDPO1rdzyzdZ7lHSGZ4M=,iv:jDGRC8Cg5NDUPUGdGvwk/kdmmLTEHQH1x2tIOWt2Ems=,tag:gFab0GHJkyKNq5eRYDlT9A==,type:comment]
    #ENC[AES256_GCM,data:3IRo99IKtZNDxOnwBQDOVy4FnAzddTN0MV43y/X7IA/6ezaPYPgpFg==,iv:WKuWE88iaESbh0DxMeXv+uclPtF9Yy9fyGfrLUl/dvU=,tag:92eNLTouK0YpmfD0UFPhFA==,type:comment]
    #ENC[AES256_GCM,data:bukdaWvn7PD2kH1SiKpOimyq1q0WSQquFTHF+Y/PAxsrstOSew==,iv:KJDkJYJ2rzszVzFsSL0AvU52imH7O2P07NqliN+D9V4=,tag:vt07uwMjh7PznmGOVsebag==,type:comment]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWNCaTF6cFFqZll0a1FD
            NkRwditvODVON3pyU3ZBdmNLNE13cDMwMEJvCnQzZmpNak1UL1VhYndPTWlsOG9S
            UlJ2ajJ1TTU2Zlhlc2s4R0V6eVZPZTAKLS0tIFkwVFhoRTg5VjBaTVIrMGoxVGRi
            dHhYOGpvWXVMMnZPdEZPRW1kcE9QZzgKnrTJ/GYM+DkGQAbx9okd+Ir5DV1YJSFw
            7dhEflmWWJXm/nPTdw4EiRbluMcnbr/ji1JHpbs35lfUGhzKjhUSnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T08:06:04Z"
    mac: ENC[AES256_GCM,data:Hkb9NBGyTol541bBJJ4PU5m/je5Hq6a4lAbGUkv4XrGrQOGZxoe0/JhSNwuQ8qW73S9w8pplFJSXvR4j2Yte71xuRTzWwBWkEl7v+fUz5iyIsFjOcS3X1Iudvv0Kz7cGqrn9lp1egVW0KIq9k8QBMTIKUMXtVy8Y5aypN5HJv10=,iv:XiCRnlJP7bO9mXIsT+5w4ohKKCxF4GaY5hdQGO8FvfY=,tag:z389S29ny3wvK3xA+yJ+QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:n2Q=,iv:13Ovy8KS78KwGmjUM4xY5aIvSmg4sdg+TqigC9XaNQQ=,tag:5jHeXxZNrTSUpDubZuhUnQ==,type:str]
kind: ENC[AES256_GCM,data:fB4b/m3k,iv:EIvezfwh55b45vzUWyy8Kysu5619BZykYfUdmlTnJ1s=,tag:/oGBbiDcJ9zEJeyKNQhEEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mM/zNskHkAf9cYrVyCR1xs4=,iv:A25SkNgU9OHInrx/YVezEwYZBSxyeQVgHBSW/oQY1uU=,tag:exRq7EGxvMNotKEuB89f2A==,type:str]
    namespace: ENC[AES256_GCM,data:B8nC2o0Y5t3+IvcSOhxa,iv:jtqDaIfswlOZIfAr20O2BdAK/kCfLL1FUuU8SzqhnCM=,tag:4TnvKHVfa5jhoMqk9eOaWA==,type:str]
stringData:
    AUTH_TRUST_HOST: ENC[AES256_GCM,data:k1BM/A==,iv:g6uMarflW6yNbobaaUHvSO43cMY7JlkGwthVW02Qkwo=,tag:fcwzQb6HKxEnThrvqLaLEQ==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:LU2LTHCvNW8qwolRZbytSGX6+qLUHoTz5e1O,iv:Nta2oCJ2dj5i+nd426sPmg2p/cZqss2EkFpFxY29Oqg=,tag:tDBySXEg5K3IV/NpjBilbA==,type:str]
    BACKEND_URL: ENC[AES256_GCM,data:faX/YaKlASUkn2FMgq/ouaqb5Jnyk4ZmSLgv2AMm,iv:GBSve8cJEYmIKKTprB5trhNz5No0NOvvIV24m0oUACU=,tag:nhO9Wl3CjSrXoiQJsCiX0Q==,type:str]
    NEXT_PUBLIC_BE_WS_URL: ENC[AES256_GCM,data:LIXDnMoR3+79k0ZwCdLXhBFYQHcGhC0eVw==,iv:FmJYttyTVRgPXppBdDX0nT3ZByk/XvX9KLgMnpeAXvc=,tag:epxhre0ONzJ/CMCgRaK4PA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:zQNyP9QEjSktuFpqa7EV2gU1tXAtqKHr1eZvCQvtdb9E2qS3ZNmAux43ydA=,iv:qu3hNJhxlTCIpyZ759J6i2q+1YqrH9wHyNNDD1quo38=,tag:73z01pohiY43w/litSunUA==,type:str]
    ZITADEL_ISSUER: ENC[AES256_GCM,data:YI7ZNB/Mm5LOK06UJx+IL1p6A5iq43P7+WeY,iv:D3CTh+44RSgsItuqfKdBoVmhVYN9R0HrmEypxBohnZg=,tag:FYQZ+44UFTa6+R95+9qW4w==,type:str]
    ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:lvdUco37f23VTlONpc9Sfp5h,iv:M+70msgt4RQiA+WAckecEal6AAxROQevaov10C9uHg4=,tag:TdRHFuSYIRxfr8CxSx1vpQ==,type:str]
    ZITADEL_ORG_ID: ENC[AES256_GCM,data:jzDzcGDfXNwyNYGSXIVYWdgZ,iv:TlT3CfnfAGYCKXwlLIwzuY84JVkQqFs0xdfqztiQFGI=,tag:hAieORj7Kpm0+9Xj7/66Xw==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWNCaTF6cFFqZll0a1FD
            NkRwditvODVON3pyU3ZBdmNLNE13cDMwMEJvCnQzZmpNak1UL1VhYndPTWlsOG9S
            UlJ2ajJ1TTU2Zlhlc2s4R0V6eVZPZTAKLS0tIFkwVFhoRTg5VjBaTVIrMGoxVGRi
            dHhYOGpvWXVMMnZPdEZPRW1kcE9QZzgKnrTJ/GYM+DkGQAbx9okd+Ir5DV1YJSFw
            7dhEflmWWJXm/nPTdw4EiRbluMcnbr/ji1JHpbs35lfUGhzKjhUSnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T08:06:04Z"
    mac: ENC[AES256_GCM,data:Hkb9NBGyTol541bBJJ4PU5m/je5Hq6a4lAbGUkv4XrGrQOGZxoe0/JhSNwuQ8qW73S9w8pplFJSXvR4j2Yte71xuRTzWwBWkEl7v+fUz5iyIsFjOcS3X1Iudvv0Kz7cGqrn9lp1egVW0KIq9k8QBMTIKUMXtVy8Y5aypN5HJv10=,iv:XiCRnlJP7bO9mXIsT+5w4ohKKCxF4GaY5hdQGO8FvfY=,tag:z389S29ny3wvK3xA+yJ+QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
