---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: opencsp-impersonator
  namespace: teleport
spec:
  allow:
    logins: ['ubuntu', 'root']
    node_labels:
      '*': '*'
    impersonate:
      users: ['*']
      roles: ['*']
    rules:
      - resources: ['user']
        verbs: ['list', 'read']
      - resources: ['role']
        verbs: ['list', 'read']
---
apiVersion: resources.teleport.dev/v1
kind: TeleportBotV1
metadata:
  name: opencsp-be-bot
  namespace: teleport
spec:
  roles:
    - opencsp-impersonator
---
apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: opencsp-be-bot
  namespace: teleport
spec:
  roles: [Bot]
  join_method: kubernetes
  bot_name: opencsp-be-bot
  kubernetes:
    type: in_cluster
    allow:
      - service_account: "opencsp-console:opencsp-tbot"