apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel-miiml
  namespace: zitadel
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: zitadel
      version: "9.26.0"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: zitadel-postgresql
      namespace: zitadel
  valuesFrom:
    - kind: Secret
      name: zitadel-secrets
      valuesKey: values.yaml

  values:
    fullnameOverride: "zitadel-miiml"
    zitadel:
      configmapConfig:
        ExternalDomain: zitadel.miiml.org
        ExternalPort: 443
        ExternalSecure: true
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: zitadel-postgresql
            Port: 5432
            Database: zitadel
            MaxOpenConns: 20
            MaxIdleConns: 10
            MaxConnLifetime: 30m
            MaxConnIdleTime: 5m
            User:
              Username: zitadel
              SSL:
                Mode: disable
            Admin:
              Username: postgres
              SSL:
                Mode: disable
        SystemAPIUsers:
          - system-user-1:
              KeyData: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2MytPVnp2bnk1bTdZcG45Q0IraQpzdGJPbTdjeDE1UnJTZXN2UG1xQUJIdDBoMjB2RzdJVmEzQjVKRk5KK00rMjBPZ0szeUpKMzV3S2piVEo1dUNJClU5ZStXbnI1VE8wWVFNdHI5ajFhU1RGNXc4T2Mza2pqOVE0ellnazNLMWk5YU9UUnRtTVRQL0FieExkZldJbzMKL2FxR1hVWlhaQWZwMnJOUkt0ckxkaTZsWEo1ckFkeVJyeFhLanovTC9XQjFUNVZCcmN6c09RdGtkMW1CbUJqMQo5Y01ndC9Kbno2aE1PM1VueWFjclpVUEpSeEs2YXdUY1pkeVZDWHMwdXlFUVgyYjlQRnUwMlpSa3ByZGs1QUdCCmEzaFN6M3ZYbDl2amlMNTFnbnFWaXJGK3orTjFtVExnOEVxRjZYUnJkVUZ2QXoyU2k0V050UmxMazNVamp6MDAKTlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
              Memberships:
                - MemberType: System
                  Roles:
                    - "SYSTEM_OWNER"
                    - "IAM_OWNER"
    service:
      type: NodePort
      protocol: grpc
      appProtocol: kubernetes.io/h2c
    postgresql:
      enabled: false
