apiVersion: ENC[AES256_GCM,data:KmQ=,iv:fHvzH+RULwIb8UdyJAsWtryssUPfBvQNbP3Pu2J7qNo=,tag:85NrfKB8LlwfQLjwOzRpaA==,type:str]
kind: ENC[AES256_GCM,data:YTez+ZT3,iv:vf8Udk1DFgINDSx3OVr4QTpAjpYSEQ6EfqjPO/RrvKM=,tag:NYdGtvT2cloZpg1wfNDPYQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:33KwCu0J6bS1v4avf34h,iv:/HkA1EAa9DWGq/XHgCOcKWyaJd4blDQOiw1os+gTY3E=,tag:dY8bfnt7AaS6S1AIrqKkwQ==,type:str]
    namespace: ENC[AES256_GCM,data:pJT7itbM7g==,iv:R35unX/W6PPpWI5hPlqcjqblvR2ehUZuXHqOpNJODBM=,tag:BglpKUhK75Oia2mswUZH5Q==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:SQJ27qhVVKzDA8lNGfdvv0Lju/j7kkutDr5RSswJy8iN+yc6pdnXWvhKnAqx7XiRthK0oXzRUQUA69sh8P+cY1zQHEhgbzL/Fnwelod9BqJF3S0uib5+JnlWZbbx49rjY3VvVqGuC9cWkw+H2LjeAk6l07IFrjXjvleHhEDHCgw1QsT6VLxeo9/LkQ/yjAx6Ivc7XgZpqrJjN08sbHGngO1gduPnDvnzTc3I4hK5ySyU59qnpNuC0SRqNVuZXCzipPgugtkq22EbEm4L+jZvzCkybBu3oSAtYvmfUQrhlokbXwLXhpWC57r7WmUfIqJTq/OY1rdVEpvDxKwI0JfTm0Lhw7E57BgbGak+ax2DMu5yXVIodFECjUO9gNuwB6zpThH1u53X5PEVJGPBFv0641eISPb995qMSlCvA9P60foa7RIbu8CdMNtSCzgF/0zqrMuC/1VnZyWw+MkhAgeKWFZdFa2bEJ9Kt2t4zwu6dQVw0Tedwm+t0+LWQrvMsToheq4Uaj3L1TI0UuSqhPrYUuNgiG5A497IxLvK5s29TazurwNsX6cwmUZrJPIhczydmbJFZKeFtaOUsO5oZ2IuI0/WHuWpC+fpfgb2hzoPJxiAGAwQgvuAqzEkDgxjs8DIwd+1GxTeKS2fs/3H0BQIIGKHe7ihaJoNWFHeLHqAu+GwoYJSMAtiuRORKS+7PS3b936nK6sg3femEJ7Md5IkHSSPpL12+gjft5hIWTKAHEE7kX1jWzp4VEe4jJ7bQdi81uPOW33QguU3,iv:26cPMGU82eIUhsCLL9ml6zTMli9ckt1Itidzijszy/0=,tag:I/lHdQS0vhlyYQJqyIV1fA==,type:str]
    postgresql-values.yaml: ENC[AES256_GCM,data:a81mrAq5rZ5X62v7ikw+uDGyYrmS96+k3PZa/kVjRdZsO0rOCtCmVOdOk6mEOGrWsUYq/VjyOiDxFZIXk1Kit6HpJqhrTrlwjehSamGLLE2xV5DkPmMH0nvXRwIgni2THHnJzNNg+9kUZtmApJ8ydxaAAbK5lRjGbs7lqfhMRUwpY3S7fcZ7Y2XlVZ/Qtq9NSju0Dg==,iv:AGXio98oRI/8890o77a9oOjlBJyUqTwG4dP1cNRwxks=,tag:QOX+ikSIwC0buk9RLtLSHw==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWFFXaEJyUGQwd1Q0ZGZC
            cWNUZEZ0UWlydUNHVWpoTjRZL2N0OW1MamlVCjZBYlc2QU4rSXBjSXE3L1RGczdU
            OWhrOHNoakNuQ09YU3NkcGF3TzM5UXMKLS0tIEVYTk44ZkpZTTNhbGhFK01pN3hW
            SWpwTktJSG5UUnFkY044UkM2UVc3cUkKMGe8GaCQoROqY79Gii7vuf9Dm1GOWtSa
            HylLCqhiUpwgul2Fcs6vOpaFrmJc7eiBJYYTeB198tjFRzOrEJSfTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T08:08:43Z"
    mac: ENC[AES256_GCM,data:V9TPdfisgHWvJAQvUZcetKPVTg2zcBvBWyGVZE/j9nOxB/WI4YgmRghGhdh3USvcQECOkJrKG7uGZRTddoiHnIehceDQntR9Y6vFE7tXrIbR/YZp8BfscVPgENeQx5xwj8XvEIZJjJO8vbts7Qcj4onEf64HH76zRUC8vYgJk1g=,iv:M7TYlM5cdl6BlHGZOme5pkEwBOPuhh/m5UWxDVLHA/4=,tag:LrfVHOWNsn5vsVp5T/y27g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
