# teleport 자체 인증서 말고 cert-manager로 발급받은 인증서 사용하려면 위 주석 해제
# 그리고 release.yaml에서 tls.existingSecretName: teleport-tls-all로 설정
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-tls-all
  namespace: teleport-miiml
spec:
  secretName: teleport-tls-all
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: teleport.miiml.org
  dnsNames:
    - teleport.miiml.org
    - "*.teleport.miiml.org"

